# Site settings
title: re:blog
header-img: img/home-bg.jpg
email: sriramsh@buffalo.edu
description: "fastboot flashall"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: 
github_username:  SriramBms
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
